name: Build Telegram X

on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Init submodules
        run: |
          git submodule init
          git config submodule.vkryl/leveldb.url https://github.com/TGX-Android/leveldb
          git config submodule.vkryl/core.url https://github.com/TGX-Android/X-Core
          git config submodule.vkryl/td.url https://github.com/TGX-Android/tdlib-utils
          git config submodule.vkryl/android.url https://github.com/TGX-Android/X-Android
          git config submodule.tdlib.url https://github.com/TGX-Android/tdlib
          git submodule update --init --depth=1 vkryl/leveldb vkryl/core vkryl/td vkryl/android tdlib

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk
